
# hello is the executable which depends on hello_linux.c
# when the .c file changes, it means we need to
# make the executable again by running the commands
hello: hello_linux.c
	gcc hello_linux.c -o hello
	echo "did compile!"



